
name: Deploy

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY_B64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -lah ~/.ssh
          ssh-keyscan -H 13.41.185.213 >> ~/.ssh/known_hosts

      # - name: Deploy to EC2
      #   run: |
      #     ssh ubuntu@13.41.185.213 << 'EOF'
      #       # Go to app directory or create it if it doesn't exist
      #       cd ~/app || mkdir -p ~/app && cd ~/app
            
      #       # If repo doesn't exist, clone it; otherwise, pull latest changes
      #       if [ ! -d "lft-barebones" ]; then
      #         git clone https://github.com/pgmoir/lft-barebones
      #       fi
            
      #       cd lft-barebones
      #       git pull
            
      #       # Install dependencies
      #       npm install
            
      #       # Restart app using PM2
      #       pm2 stop all || true
      #       pm2 start server.js --name "node-app"
      #       pm2 save
      #     EOF

      - name: Deploy to EC2
        run: |
          # Decode the base64-encoded private key and save it to a file
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY_B64 }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Set the correct permissions for the private key
      
          # Copy files from the runner to the EC2 instance using scp
          cd ~/app || mkdir -p ~/app && cd ~/app
          scp -i ~/.ssh/id_rsa -r ./ ubuntu@13.41.185.213:/app

          # Install dependencies
          npm install
          
          # Restart app using PM2
          pm2 stop all || true
          pm2 start server.js --name "node-app"
          pm2 save
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY_B64 }}
        
